const Router = require('express')
const router = new Router()
const productRouter = require('./productRouter')
const bouquetRouter = require('./bouquetRouter')
const userRouter = require('./userRouter')
const ordersRouter = require('./ordersRouter')
const flowersRouter = require('./flowersRouter')
const basketRouter = require('./basketRouter')
const reviewPhotoRouter = require('./reviewPhotoRouter')
const reviewTextRouter = require('./reviewTextRouter')

router.use('/user', userRouter)
router.use('/products', productRouter)
router.use('/bouquet', bouquetRouter)
router.use('/orders', ordersRouter)
router.use('/flowers', flowersRouter)
router.use('/basket', basketRouter)
router.use('/reviewPhoto', reviewPhotoRouter)
router.use('/reviewText', reviewTextRouter)

module.exports = router
