const uuid = require('uuid')
const path = require('path');
const ApiError = require('../error/ApiError');

let Bouquet = [
    {id: 1, name: "Букет из разноцветных ромашек роз пионов и лилий", price: [{size: "Малый", value: 1290}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_box', color: 'c_white', img: [{id: 1, src: `https://via.placeholder.com/150/771796`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847878, rating: 1},
    {id: 2, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 129}, {size: "Средний", value: 155}, {size: "Большой", value: 180}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_bouquet', color: 'c_red', tag: 'Новинка', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847870, rating: 2},
    {id: 3, name: "Букет из разноцветных пионов", price: [{size: "Малый", value: 2500}, {size: "Средний", value: 3500}, {size: "Большой", value: 1900}], flowers: [ "roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_bouquet', color: 'c_blue', tag: 'Новинка', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847860, rating: 3},
    {id: 4, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 4600}, {size: "Средний", value: 1540}, {size: "Большой", value: 1799}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_red', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847850, rating: 4},
    {id: 5, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 2700}, {size: "Средний", value: 1550}, {size: "Большой", value: 1900}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 6, name: "Букет из разноцветных пионов", price: [{size: "Малый", value: 990}, {size: "Средний", value: 1540}, {size: "Большой", value: 1800}], flowers: [ "roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_bouquet', color: 'c_blue', tag: 'Новинка', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847860, rating: 3},
    {id: 7, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 6000}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_red', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847850, rating: 4},
    {id: 8, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 7000}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 9, name: "Букет из разноцветных пионов",price: [{size: "Малый", value: 2300}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_bouquet', color: 'c_blue', tag: 'Новинка', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847860, rating: 3},
    {id: 10, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 4500}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_red', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847850, rating: 4},
    {id: 11, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 4500}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: ["roses", "tulips"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_red', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847850, rating: 4},
    {id: 12, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 13, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 14, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 15, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 16, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 17, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 18, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 19, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
    {id: 20, name: "Букет из разноцветных роз", price: [{size: "Малый", value: 1254}, {size: "Средний", value: 1550}, {size: "Большой", value: 1800}], flowers: [ "roses"], description: [{name: "Гербера оранжевая", value: 11}, {name: "Гвоздика однобутонная розовая", value: 7}, {name: "Хризантема кустовая Филин Грин", value: 5}, {name: "Роза Шангри Ла", value: 29}, {name: "Роза Пенни Лейн", value: 29}], pack: 'p_basket', color: 'c_yellow', tag: 'Акция', img: [{id: 1, src: `https://via.placeholder.com/150/92c952`}, {id: 2, src: `https://via.placeholder.com/150/771796`},{id: 3, src: `https://via.placeholder.com/150/771796`},{id: 4, src: `https://via.placeholder.com/150/771796`}], date: 1676847834, rating: 5},
]

class BouquetController {
    create(req, res, next) {
        try {
            let {name, price, flowers, pack, color, rating, description} = req.body
            const {img} = req.files
            let fileName = uuid.v4() + ".jpg"
            img.mv(path.resolve(__dirname, '..', 'static', fileName))
            const id = +Bouquet.length
            const date = Date.now()
            Bouquet.push({id: id, name: name, price: price, flowers: flowers, pack: pack, color: color, date: date, rating: rating, img: fileName, description: description});
            return res.json(Bouquet)
        } catch (e) {
            next(ApiError.badRequest(e.message))
        }

    }

    getAll(req, res) {
        let {page} = req.query
        let limit = 9
        let start = page * limit - limit
        let end = start + limit
        let bouquets = Bouquet.slice(start, end);
        return res.json(bouquets)
    }

    getOne(req, res) {
        const {id} = req.params
        const bouquet = Bouquet.find(b => b.id === +id)
        return res.json(bouquet)
    }
}

module.exports = new BouquetController()
